[workspace]
authors = ["Miroslav Georgiev <miro.georgiev@gmail.com>"]
channels = ["conda-forge"]
name = "darwins_rockets"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
pygame = ">=2.6.1,<3"
numpy = ">=2.3.1,<3"
pixi-pycharm = ">=0.0.8,<0.0.9"
coverage = ">=7.9.2,<8"
